##################################################################################
# Cloudify Ansible built in types and plugins definitions.
##################################################################################
plugins:
  ansible:
    executor: central_deployment_agent
    source: https://github.com/earthmant/cloudify-ansible-plugin/archive/{{ plugin_branch }}.zip