plugins:

  ansible:
    executor: central_deployment_agent
    source: https://github.com/cloudify-cosmo/cloudify-ansible-plugin/archive/dev.zip
    package_name: cloudify-ansible-plugin
    package_version: '2.0.0.dev0'
