- hosts: all
  tasks:
    - name: Example from an Ansible Playbook
      win_ping:
        data: pong
        register: out
    - name: ping runtime property
      cloudify_runtime_property:
        path: ping
        value: out.stdout_lines
